id = "leaf"
name = "Leaf"
description = "Leaf templating language support for Swift Vapor framework."
version = "0.1.0"
schema_version = 1
authors = ["Alan"]
repository = "https://github.com/your-repo/leaf-zed-plugin"

[grammars.leaf]
repository = "https://github.com/tree-sitter/tree-sitter-html"
commit = "bfa075d83c6b97cd48440b3829ab8d24a2319809"